---
- hosts: vmlab
  become: yes
  vars:
    seneca_id: "pkandasamy7"

  tasks:

    - name: ensure apache is updated
      yum:
        name: httpd
        state: latest

    - name: install epel-release repo
      yum:
        name: epel-release
        state: present

    - name: remove tree package
      yum:
        name: tree
        state: absent

    - name: set hostname
      hostname:
        name: "{{ seneca_id }}"

    - name: create new user
      user:
        name: "{{ seneca_id }}"
        shell: /bin/bash
        state: present
        groups: wheel
        append: yes

    - name: create .ssh directory
      file:
        path: "/home/{{ seneca_id }}/.ssh"
        state: directory
        mode: "0700"
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"

    - name: copy authorized_keys for new user
      copy:
        src: "~/.ssh/id_rsa.pub"
        dest: "/home/{{ seneca_id }}/.ssh/authorized_keys"
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: "0600"

    - name: create lab directories
      file:
        path: "/home/{{ seneca_id }}/ops445/lab{{ item }}"
        state: directory
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: "0755"
      loop: [1,2,3,4,5,6,7,8]
